version: 2.1

jobs:
  runner:
    # Add your config here
    machine: true
    resource_class: runner-egrapp/support-demo
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
  testing:
    jobs:
      - runner